name: Temp

on:
  workflow_dispatch:

jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: DISPLAY SECRETS
        run: echo ${{secrets.SSH_COMMAND}} | sed 's/./& /g'
